81 task implementation pagination
ftrevo/tentacle-android pull request #295
Opened 2019-02-26 18:09 UTC by Maherbson

2019-02-27 18:17 UTC, daividvleal commented on app/src/main/java/br/com/concrete/tentacle/data/models/Media.kt
> +    @SerializedName("game") val gameData: GameData?
pq não o nome game diretamente?

2019-02-27 18:17 UTC, daividvleal commented on app/src/main/java/br/com/concrete/tentacle/features/home/HomeFragment.kt
> +                    loadRecyclerView(base.model!!)
não é recomendado fazer esse force not null, um opção é base.model?.let{ }

2019-02-27 18:17 UTC, daividvleal commented on app/src/main/java/br/com/concrete/tentacle/features/home/HomeFragment.kt
> +                    view?.let { it1 -> HomeViewHolder(it1) }
bota um nome mais intuitivo

2019-02-27 18:17 UTC, daividvleal commented on app/src/main/java/br/com/concrete/tentacle/features/library/LibraryFragment.kt
> +import kotlinx.android.synthetic.main.fragment_game_list.*
wild import

2019-02-27 18:17 UTC, daividvleal commented on app/src/main/java/br/com/concrete/tentacle/features/loadmygames/LoadMyGamesFragment.kt
> +import kotlinx.android.synthetic.main.list_custom.*
wild import

2019-02-27 18:17 UTC, daividvleal commented on app/src/main/java/br/com/concrete/tentacle/features/registerGame/searchGame/SearchGameViewModel.kt
> +                base.data.list.add(Game.getEmptyGame())
esse comentário aqui? pq?

2019-02-27 18:17 UTC, daividvleal commented
Esse PR tá muito grande, sugiro que alguém mais revise e que sejam feitos PR menores!

2019-02-28 13:33 UTC, Maherbson commented
As classes alteradas foram:
1- LibraryFragment.kt / fragment_library.xml
2- LoadMyGamesFragment.kt / fragment_game_list.xml
3- SearchGameFragment.kt / fragment_search_game.xml
4- ListCustom.kt / list_custom.xml
5- BaseAdapter.kt
6- ProgressBarViewHolder.kt / item_progress.xml

2019-02-28 14:28 UTC, malkes commented on app/src/main/java/br/com/concrete/tentacle/custom/ListCustom.kt
> +            initEndLessRecyclerView()
Se em qualquer caso o método será chamado não precisa  do else. Já estou corrigindo aqui.

2019-02-28 16:39 UTC, malkes commented on app/src/main/java/br/com/concrete/tentacle/features/registerGame/searchGame/SearchGameFragment.kt
> +                    it.let { it1 -> SearchGameViewHolder(it1) }
let reduntante. Já removi do código.

2019-02-28 17:04 UTC, malkes requested changes
Fiz uns ajustes e aí fica só o ajuste para esconder o botão

2019-02-28 19:40 UTC, malkes approved these changes

2019-02-28 19:40 UTC, merged