265 task add kebab menu
ftrevo/tentacle-android pull request #406
Opened 2019-03-13 13:04 UTC by daividvleal

2019-03-13 16:21 UTC, malkes commented on .gitignore
> +app/google-services.json
esse arquivo normalmente é de configuração de algum serviço ou Api da Google. Até o momento não estamos usando nenhum serviço que precise dele. Ou isso já é algum teste do Firebase para o Push Notification?

2019-03-13 16:24 UTC, malkes commented on app/src/main/java/br/com/concrete/tentacle/features/lendgame/LendGameActivity.kt
> +            android.R.id.home -> {
Esse evento já é tratado na BaseActivity, não precisa repetir ele aqui

2019-03-13 16:38 UTC, malkes commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-5.2-bin.zip
Precisa mudar de all para bin?
Em teoria o all tem os executáveis e a documentação e o bin apenas os binários.

2019-03-13 16:39 UTC, malkes requested changes
Comentários no código

2019-03-13 17:52 UTC, daividvleal commented on app/src/main/java/br/com/concrete/tentacle/features/lendgame/LendGameActivity.kt
> +            android.R.id.home -> {
mas eu dei um override no método... aí ele ficará sem ação caso isso não seja feito aqui

2019-03-13 17:52 UTC, daividvleal commented on .gitignore
> +app/google-services.json
é que aqui na máquina já tem esse arquivo pq eu já estava testando Firebase para o Push Notification

2019-03-13 17:52 UTC, daividvleal commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-5.2-bin.zip
eu não mexi aqui, foi automático...

2019-03-14 22:03 UTC, daividvleal commented
No changes on code where done, just fix the review comment;

review just TestDeleteMenuButton;

2019-03-14 23:11 UTC, malkes approved these changes

2019-03-14 23:11 UTC, merged